data <- read.csv("~/R/Exploratory/exdata-data-household_power_consumption/household_power_consumption.txt", sep=";", quote="")
data<-subset(data,Date == "1/2/2007" | Date == "2/2/2007")
png("Plot1.png", width = 480, height = 480, bg = "transparent", units = "px")
hist(as.numeric(as.character(data$Global_active_power)),main="Global Active Power",xlab="Global Active Power (kilowatts)",col="red")
dev.off()