data <- read.csv("~/R/Exploratory/exdata-data-household_power_consumption/household_power_consumption.txt", sep=";", quote="")
data<-subset(data,Date == "1/2/2007" | Date == "2/2/2007")
data$DateTime<-as.POSIXct(paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
png("Plot3.png", width = 480, height = 480, bg = "transparent", units = "px")
plot(data$DateTime,as.numeric(as.character(data$Sub_metering_1)),xlab="",ylab="Energy sub metering",type="l")
lines(data$DateTime,as.numeric(as.character(data$Sub_metering_2)),type="l",col="red")
lines(data$DateTime,as.numeric(as.character(data$Sub_metering_3)),type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.off()